server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://112.221.66.174:3306/sunflowerdb
=======
    url: jdbc:mysql://112.221.66.174:3306/sunflowerDB
>>>>>>> 814a9c68f195ae2646d8a46aa62ac41e01908759
    username: gangnam
    password: gangnam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: mapper/*.xml
payment:
  client-key: test_ck_0RnYX2w532Dg0KN6dLYgrNeyqApQ
  secret-key: test_sk_Poxy1XQL8RbKZELvzdGL87nO5Wml
  widget-secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  base-url: https://api.tosspayments.com/v1/payments
  success-url: "http://112.221.66.174:8081/api/v1/payments/toss/success"
  fail-url: "http://112.221.66.174:8081/api/v1/payments/toss/fail"
  cancel-endpoint: /cancel
  confirm-endpoint: /confirm
file:
  upload-dir: "C:\\20240801-gangnam\\Project\\img"  # Windows 경로에서 백슬래시 두 개 사용
  base-url: "http://112.221.66.174:8081/images/"
