server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://112.221.66.174:3306/sunflowerDB
    username: gangnam
    password: gangnam
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapper/*.xml
